#spring:
#  application:
#     name: api-gateway
#
## api gatway config
#
#  cloud:
#    gateway:
#      routes:
#        -id: order-service
#         uri: lb://ORDER-SERVICE
#         predicates:
#          -path=/api/v1/orders/**
#          
#         

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
