spring:
  application:
    name: config-server

  cloud:
    config:
      server:
       git:
         uri: https://github.com/Tejas-Gopale/ecommerce-config-server
         username: tejas-gopale         

      
         default-lable : master
          
server:
  port: 8888
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka 
      
    