spring:
  application:
    name: config-server
    
  cloud:
   config:
     server:
       git:
          uri: https://github.com/Tejas-Gopale/ecommerce-config-server # URL of your Git repository
          username: tejas-gopale # Optional: If your repo is private
          password:  # Optional: If your repo is private
          default-label: master
       
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  
      
server:
  port: 8888