management:
  health:
    circuitbreakers:
      enabled: true
    endpoints : 
      web: 
       exposure:
        include: "*"
    endpoint :
      health:
       show-details: always
      


resilience4j:
  retry:
    instances:
      inventoryretry:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - org.springframework.web.client.HttpServerErrorException
        ignore-exceptions:
          - org.springframework.web.client.HttpClientErrorException$NotFound
  ratelimiter:
    instances:
      inventoryRateLimiter:
        limit-for-period: 1
        limit-refresh-period: 10ms
        timeout-duration: 10ms
  circuitbreaker:
    instances:
      inventoryCircutBeaker:
        register-health-indicator: true
        sliding-window-size: 10
        sliding-window-type: count-based
        minimum-number-of-calls: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 3
        event-consumer-buffer-size: 10
          
        
        
          
      