INSERT INTO product (title, price, stock) VALUES ('Wireless Mouse', 599.99, 50);
INSERT INTO product (title, price, stock) VALUES ('Gaming Keyboard', 1499.00, 30);
INSERT INTO product (title, price, stock) VALUES ('Bluetooth Headphones', 2499.50, 20);
INSERT INTO product (title, price, stock) VALUES ('Laptop Stand', 799.00, 40);
INSERT INTO product (title, price, stock) VALUES ('USB-C Charger', 499.00, 60);
INSERT INTO product (title, price, stock) VALUES ('Smartphone Cover', 299.99, 100);
INSERT INTO product (title, price, stock) VALUES ('Power Bank', 999.00, 45);
INSERT INTO product (title, price, stock) VALUES ('Webcam HD', 1299.00, 25);
INSERT INTO product (title, price, stock) VALUES ('External Hard Drive 1TB', 3499.00, 15);
INSERT INTO product (title, price, stock) VALUES ('Portable Speaker', 1999.00, 35);
INSERT INTO product (title, price, stock) VALUES ('Wireless Earbuds', 1799.00, 50);
INSERT INTO product (title, price, stock) VALUES ('Fitness Band', 1599.00, 40);
INSERT INTO product (title, price, stock) VALUES ('Smart Watch', 4999.00, 20);
INSERT INTO product (title, price, stock) VALUES ('4K Monitor', 15999.00, 10);
INSERT INTO product (title, price, stock) VALUES ('Gaming Chair', 8999.00, 12);
INSERT INTO product (title, price, stock) VALUES ('Desk Lamp', 699.00, 25);
INSERT INTO product (title, price, stock) VALUES ('Graphic Tablet', 5999.00, 8);
INSERT INTO product (title, price, stock) VALUES ('Wireless Router', 2499.00, 18);
INSERT INTO product (title, price, stock) VALUES ('Noise Cancelling Headphones', 3999.00, 15);
INSERT INTO product (title, price, stock) VALUES ('Laptop Bag', 1499.00, 30);
INSERT INTO product (title, price, stock) VALUES ('Memory Card 64GB', 799.00, 80);
INSERT INTO product (title, price, stock) VALUES ('Tripod Stand', 1299.00, 20);
INSERT INTO product (title, price, stock) VALUES ('Smart LED Bulb', 699.00, 50);
INSERT INTO product (title, price, stock) VALUES ('VR Headset', 11999.00, 5);
INSERT INTO product (title, price, stock) VALUES ('Gaming Console', 34999.00, 7);
INSERT INTO product (title, price, stock) VALUES ('Wireless Printer', 6999.00, 10);
INSERT INTO product (title, price, stock) VALUES ('Microphone', 2999.00, 12);
INSERT INTO product (title, price, stock) VALUES ('Projector', 8999.00, 6);
INSERT INTO product (title, price, stock) VALUES ('Action Camera', 14999.00, 8);
